/* ADDRESS */

// 초기 상태
export const SET_INITIAL_SEARCH = "SET_INITIAL_SEARCH";

// 주소 검색
export const GET_ADDRESS_LIST ="GET_ADDRESS_LIST";
export const GET_ADDRESS_LIST_SUCCESS = "GET_ADDRESS_LIST_SUCCESS";
export const GET_ADDRESS_LIST_ERROR = "GET_ADDRESS_LIST_ERROR";

// 주소 리스트 item 선택
export const SELECT_ADDRESS_ITEM = "SELECT_ADDRESS_ITEM";
export const DESELECT_ADDRESS_ITEM = "DESELECT_ADDRESS_ITEM";

// 현재 위치 검색
export const GET_CURRENT_LOCATION_ADDRESS =  "GET_CURRENT_LOCATION_ADDRESS";
export const GET_CURRENT_LOCATION_ADDRESS_SUCCESS =  "GET_CURRENT_LOCATION_ADDRESS_SUCCESS";
export const GET_CURRENT_LOCATION_ADDRESS_ERROR =  "GET_CURRENT_LOCATION_ADDRESS_ERROR";

export * from './address/actions';
