/* ADDRESS */

// 초기 상태
export const SET_INITIAL_SEARCH = "SET_INITIAL_SEARCH";

// 주소 검색
export const GET_ADDRESS_LIST_REQUEST ="GET_ADDRESS_LIST_REQUEST";
export const GET_ADDRESS_LIST_SUCCESS = "GET_ADDRESS_LIST_SUCCESS";
export const GET_ADDRESS_LIST_FAILURE = "GET_ADDRESS_LIST_FAILURE";

// 주소 리스트 item 선택
export const SELECT_ADDRESS_ITEM = "SELECT_ADDRESS_ITEM";
export const DESELECT_ADDRESS_ITEM = "DESELECT_ADDRESS_ITEM";

// 현재 위치 검색
export const GET_CURRENT_LOCATION_ADDRESS_REQUEST =  "GET_CURRENT_LOCATION_ADDRESS_REQUEST";
export const GET_CURRENT_LOCATION_ADDRESS_SUCCESS =  "GET_CURRENT_LOCATION_ADDRESS_SUCCESS";
export const GET_CURRENT_LOCATION_ADDRESS_FAILURE =  "GET_CURRENT_LOCATION_ADDRESS_FAILURE";

export * from './address/actions';

// 최신 로또 회차 검색
export const GET_LATEST_LOTTO_ROUNDS_REQUEST = "GET_LATEST_LOTTO_ROUNDS_REQUEST";
export const GET_LATEST_LOTTO_ROUNDS_SUCCESS= "GET_LATEST_LOTTO_ROUNDS_SUCCESS";
export const GET_LATEST_LOTTO_ROUNDS_FAILURE = "GET_LATEST_LOTTO_ROUNDS_FAILURE";

// 로또 번호 검색
export const GET_WIN_LOTTO_NUMBER_REQUEST = "GET_WIN_LOTTO_NUMBER_REQUEST";
export const GET_WIN_LOTTO_NUMBER_SUCCESS= "GET_WIN_LOTTO_NUMBER_SUCCESS";
export const GET_WIN_LOTTO_NUMBER_FAILURE= "GET_WIN_LOTTO_NUMBER_FAILURE";

export * from './lottonumber/actions';
