/* ADDRESS */

export const GET_ADDRESS_LIST ="GET_ADDRESS_LIST";
export const GET_ADDRESS_LIST_SUCCESS = "GET_ADDRESS_LIST_SUCCESS";
export const GET_ADDRESS_LIST_ERROR = "GET_ADDRESS_LIST_ERROR";
export const SELECT_ADDRESS_ITEM = "SELECT_ADDRESS_ITEM";
export const DESELECT_ADDRESS_ITEM = "DESELECT_ADDRESS_ITEM";



export * from './address/actions'

